name: picpas
title: PicPas
version: '0.8.7'
summary: Pascal cross-compiler for Microchip 8-bit PIC microcontrollers.
description: |
  PicPas is a Pascal compiler and IDE, written in Lazarus, which generates executable code for Baseline and Mid-range PIC microcontrollers.

  No additional libraries or software required to compile. PicPas generates the *.hex file directly.

  PicPas works with a simplified version of the Pascal language, that has been adapted to work with limited resources small devices.

  Currently, it only supports basic types.

  It includes a complete IDE/debugger/simulator to facilitate the development.

  The PicPas compiler includes advanced optimization options so the code obtained is generally more compact than the obtained with other compilers.
confinement: strict
base: core20
grade: stable
icon: "Install/snap/local/PicPas.png"
license: NLPL

parts:
  picpas:
    plugin: nil
    source: .
    source-type: local
    build-packages: 
    - fpc
    - lazarus
    - lcl
    - lcl-utils
    override-build: |
      snapcraftctl build
      lazbuild --build-mode=Debug Source/PicPas.lpi
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/usr/bin
      install -s -m 755 PicPas-linux $SNAPCRAFT_PART_INSTALL/usr/bin
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/language
      install -m 644 language/PicPas.po $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/language
      install -m 644 language/PicPas.de.po $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/language
      install -m 644 language/PicPas.es.po $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/language
      install -m 644 language/PicPas.qu.po $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/language
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/usr/share/applications
      install -m 755 Install/snap/local/PicPas.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      install -m 644 Install/snap/local/PicPas.png $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      install -d -m 755 $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/syntax
      install -m 644 syntax/PicPas_AsmPic.xml $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/syntax
      install -m 644 syntax/PicPas_C.xml $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/syntax
      install -m 644 syntax/PicPas_PIC16.xml $SNAPCRAFT_PART_INSTALL/usr/share/PicPas/syntax
      cp -r units $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      cp -r samples $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      cp -r devices10 $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      cp -r devices16 $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      cp -r devices17 $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      cp -r devices18 $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      cp -r themes $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
      install -m 644 PicPas-linux.xml $SNAPCRAFT_PART_INSTALL/usr/share/PicPas
    stage:
    - usr
    - usr/bin
    - usr/share/PicPas
    - usr/share/applications/PicPas.desktop
    - usr/share/pixmaps
    stage-packages:
    - libgtk2.0-0

apps:
  picpas:
    command: usr/bin/PicPas-linux
    desktop: usr/share/applications/PicPas.desktop
    plugs:
    - desktop
    - x11

layout:
  /usr/share/PicPas:
    bind: $SNAP/usr/share/PicPas
